[package]
name = "freq"
version = "0.1.0"
authors = ["Alexey Shuksto <alexey@shuksto.name>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
fnv = "1"
regex = "1"
